### ISSUE TITLE
pnpm 12.x native binary never installed, falls back to Node-interpreted mode

### ISSUE THREAD

**Issue by attila** [moonrepo/proto#1117]
### What version?

0.62.0

### Which command?

proto install pnpm 12.3.4

### What happened?

pnpm 12 changed its npm package from a self-contained JS bundle into a wrapper plus a platform-specific native binary shipped as an `optionalDependency` (`@pnpm/exe.<platform>-<arch>`). An npm-managed install resolves that dependency and then runs the package's `install.js`, which hardlinks the native binary over the wrapper's placeholder `pnpm` file.

`download_prebuilt` in the [node-depman plugin](https://github.com/moonrepo/plugins/blob/e4b434dfb121a3da37b033f1060fa17d2275dd5e/tools/node-depman/src/proto.rs#L415) unpacks only the plain wrapper tarball for every pnpm version, pnpm 12 included, so neither the optional dependency nor `install.js` ever runs. `locate_executables` already carries a comment stating the intended contract for this case: ["nub, yarn v6+, and pnpm v12+ are a native binary and require no shims"](https://github.com/moonrepo/plugins/blob/e4b434dfb121a3da37b033f1060fa17d2275dd5e/tools/node-depman/src/proto.rs#L679), meaning it expects the tool-root `pnpm` file to already be the real binary. 

Nothing produces that state, so the two functions disagree with each other for every pnpm 12.x release.

On 0.58.2 (below `minimum_proto_version`) this failed outright:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/username/.proto/tools/pnpm/12.3.4/bin/pnpm.cjs'
```

After upgrading to 0.62.0 the same install succeeds and `pnpm --version` prints `12.3.4`, but only because pnpm's own placeholder file (`bin/pnpm.mjs`) self-heals: it lazily downloads the native binary at first run and spawns it as a Node subprocess, an extra process hop plus a network fetch on every fresh install or CI cache miss, and prints this to stderr on a TTY:

```
pnpm is running through Node.js because the script that installs its native binary was skipped.
Reinstall pnpm with its build scripts allowed to run the binary directly.
```

That message's own suggested fix does not apply here: proto never runs npm against the extracted package at all, so there is no build-script allowlist to change.

#1072 reported the same `Cannot find module '.../pnpm.cjs'` symptom for `12.0.0-rc.0` and was marked fixed by "experimental support" in 0.60.1. That fix added detection and executable-location handling for the `Pnpm12` case (the `locate_executables` branch above), but did not add the missing binary-placement step, so the bug persists for the stable 12.x line on later proto versions.

### Trace logs?

Not needed to reproduce; the placeholder file's own content (quoted below) documents the fallback path it takes when its native binary was never installed by a lifecycle script:

```
# pnpm's native binary replaces this file during installation (see
# ./install.js). Until then this hands over to ./bin/pnpm.mjs, which finds the
# installed binary or downloads one and spawns it.
```

### Operating system?

MacOS

### Architecture?

arm64

**Comment by milesj** [comment]
@attila We do reference the pnpm exe package directly and download from there: https://github.com/moonrepo/plugins/blob/master/tools/node-depman/src/package_manager.rs#L175

This _should_ be using the native files directly, not the JS ones. I'll debug a bit.

**Comment by milesj** [comment]
Fable:

-----

Verified. The issue is not reproducible on a clean install; it only reproduces from a stale install directory left behind by an older proto.

**What I tested** on macOS arm64, proto 0.62.0, which resolves pnpm to plugin `node_depman_tool:0.20.1`, in an isolated `PROTO_HOME`.

A clean `proto install pnpm 12.3.4` downloads the native package, not the wrapper. The recorded source in the tool manifest is:

```
https://registry.npmjs.org/@pnpm/exe.darwin-arm64/-/exe.darwin-arm64-12.3.4.tgz
```

The resulting tool directory holds four files, and `pnpm` is a Mach-O arm64 executable. There is no `bin/` directory, so the Node fallback path the reporter quotes does not exist. Running it under a real TTY prints `12.3.4` with no stderr warning, both directly and through the shim and the `bin` symlink.

**Where the report goes wrong.** It claims `download_prebuilt` unpacks the plain wrapper tarball for every pnpm version. It does not. The `Pnpm12` branch of `get_package_name_for_download` in [[package_manager.rs:174](https://claude.ai/epitaxy/tools/node-depman/src/package_manager.rs:174)](tools/node-depman/src/package_manager.rs:174) rewrites the package to `@pnpm/exe.<os>-<arch>`, with a `-musl` suffix on musl hosts. The two functions agree, contrary to the report.

**What actually produced the reporter's symptom.** I reproduced it by extracting the plain `pnpm` 12.3.4 tarball into the tool directory, exactly the state a pre-0.60.1 proto would leave, then running `proto install pnpm 12.3.4` on 0.62.0. It reports "has already been installed" and skips the download entirely. The stale wrapper stays, and running it prints their exact two-line warning plus a binary download. Their own timeline says the failing 0.58.2 attempt came first, which is what seeded that directory.

`proto install pnpm 12.3.4 --force` fixes it and lands the native binary.

**One real, smaller finding.** `--force` overwrites files but does not purge the directory first. After forcing over the stale wrapper, the tool directory still contains `bin/`, `dist/`, `install.js`, `native-binary.mjs`, the `pn`/`pnpx`/`pnx` scripts, and a 33 MB `pnpm-native` file that pnpm's own self-heal had downloaded. Only `pnpm` itself is corrected. That is dead weight, and it leaves a Node entry point present that a clean install would not have.
